
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'GUEST';

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'GUEST';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'MESAS';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'IT';
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ADMIN';

SELECT * FROM DBA_ROLE_PRIVS where GRANTEE LIKE 'GUEST%';
SELECT * FROM DBA_ROLE_PRIVS where GRANTEE LIKE 'MESAS%';
SELECT * FROM DBA_ROLE_PRIVS where GRANTEE LIKE 'IT%';
SELECT * FROM DBA_ROLE_PRIVS where GRANTEE LIKE 'ADMIN%';


SELECT 
	roles.GRANTEE,
	privs.OWNER,
	privs.TABLE_NAME,
	privs.PRIVILEGE
FROM
	DBA_ROLE_PRIVS roles,
	DBA_TAB_PRIVS privs
WHERE
	privs.GRANTEE = roles.GRANTED_ROLE
	AND roles.GRANTEE LIKE 'ADMIN%'
ORDER BY roles.GRANTEE, privs.TABLE_NAME, privs.PRIVILEGE;






