CREATE ROLE GUEST;
GRANT SELECT ON ACTA TO GUEST;
GRANT SELECT ON DEPARTAMENTO TO GUEST;
GRANT SELECT ON ELECCION TO GUEST;
GRANT SELECT ON MUNICIPIO TO GUEST;
GRANT SELECT ON PARTIDO TO GUEST;
GRANT SELECT ON VOTO TO GUEST;
GRANT SELECT ON VOTOSPRESIDENTE TO GUEST;
GRANT CREATE SESSION TO GUEST;


CREATE ROLE MESAS;
GRANT SELECT, INSERT ON ACTA TO MESAS;
GRANT SELECT, INSERT ON DEPARTAMENTO TO MESAS;
GRANT SELECT, INSERT ON ELECCION TO MESAS;
GRANT SELECT, INSERT ON MUNICIPIO TO MESAS;
GRANT SELECT, INSERT ON PARTIDO TO MESAS;
GRANT SELECT, INSERT ON VOTO TO MESAS;
GRANT SELECT, INSERT ON VOTOSPRESIDENTE TO MESAS;
GRANT CREATE SESSION TO MESAS;


CREATE ROLE IT;
GRANT SELECT ON ACTA TO IT;
GRANT SELECT ON DEPARTAMENTO TO IT;
GRANT SELECT ON ELECCION TO IT;
GRANT SELECT ON MUNICIPIO TO IT;
GRANT SELECT ON PARTIDO TO IT;
GRANT SELECT ON VOTO TO IT;
GRANT SELECT ON VOTOSPRESIDENTE TO IT;
GRANT CREATE TABLE TO IT;
GRANT CREATE USER TO IT;
GRANT CREATE SESSION TO IT;


CREATE ROLE ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACTA TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON DEPARTAMENTO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON ELECCION TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON MUNICIPIO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON PARTIDO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON VOTO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON VOTOSPRESIDENTE TO ADMIN;
GRANT CREATE USER TO ADMIN;
GRANT CREATE SESSION TO ADMIN;


CREATE USER guest1 IDENTIFIED BY guest1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER guest2 IDENTIFIED BY guest2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER guest3 IDENTIFIED BY guest3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
GRANT GUEST TO guest1;
GRANT GUEST TO guest2;
GRANT GUEST TO guest3;


CREATE USER mesas1 IDENTIFIED BY mesas1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER mesas2 IDENTIFIED BY mesas2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER mesas3 IDENTIFIED BY mesas3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER mesas4 IDENTIFIED BY mesas4 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
GRANT MESAS TO mesas1;
GRANT MESAS TO mesas2;
GRANT MESAS TO mesas3;
GRANT MESAS TO mesas4;

CREATE USER it1 IDENTIFIED BY it1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER it2 IDENTIFIED BY it2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER it3 IDENTIFIED BY it3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
GRANT IT TO it1;
GRANT IT TO it2;
GRANT IT TO it3;

CREATE USER admin1 IDENTIFIED BY admin1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER admin2 IDENTIFIED BY admin2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
GRANT ADMIN TO admin1;
GRANT ADMIN TO admin2;

SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE LIKE 'GUEST%';

