CREATE USER guest1 IDENTIFIED BY guest1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER guest2 IDENTIFIED BY guest2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;
CREATE USER guest3 IDENTIFIED BY guest3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;

CREATE USER mesas1 IDENTIFIED BY mesas1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER mesas2 IDENTIFIED BY mesas2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER mesas3 IDENTIFIED BY mesas3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER mesas4 IDENTIFIED BY mesas4 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;

CREATE USER it1 IDENTIFIED BY it1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER it2 IDENTIFIED BY it2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER it3 IDENTIFIED BY it3 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;

CREATE USER admin1 IDENTIFIED BY admin1 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;
CREATE USER admin2 IDENTIFIED BY admin2 DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK QUOTA UNLIMITED ON ELECCIONESTBS;


CREATE ROLE GUEST;
CREATE ROLE MESAS;
CREATE ROLE IT;
CREATE ROLE ADMIN;


GRANT SELECT ON ACTA TO GUEST;
GRANT SELECT ON DEPARTAMENTO TO GUEST;
GRANT SELECT ON ELECCION TO GUEST;
GRANT SELECT ON MUNICIPIO TO GUEST;
GRANT SELECT ON PARTIDO TO GUEST;
GRANT SELECT ON VOTO TO GUEST;
GRANT CREATE SESSION TO GUEST;


GRANT SELECT, INSERT ON ACTA TO MESAS;
GRANT SELECT, INSERT ON DEPARTAMENTO TO MESAS;
GRANT SELECT, INSERT ON ELECCION TO MESAS;
GRANT SELECT, INSERT ON MUNICIPIO TO MESAS;
GRANT SELECT, INSERT ON PARTIDO TO MESAS;
GRANT SELECT, INSERT ON VOTO TO MESAS;
GRANT CREATE SESSION TO MESAS;


GRANT SELECT ON ACTA TO IT;
GRANT SELECT ON DEPARTAMENTO TO IT;
GRANT SELECT ON ELECCION TO IT;
GRANT SELECT ON MUNICIPIO TO IT;
GRANT SELECT ON PARTIDO TO IT;
GRANT SELECT ON VOTO TO IT;
GRANT CREATE TABLE TO IT;
GRANT CREATE USER TO IT;
GRANT CREATE SESSION TO IT;


GRANT SELECT, UPDATE, INSERT, DELETE ON ACTA TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON DEPARTAMENTO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON ELECCION TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON MUNICIPIO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON PARTIDO TO ADMIN;
GRANT SELECT, UPDATE, INSERT, DELETE ON VOTO TO ADMIN;
GRANT CREATE USER TO ADMIN;
GRANT CREATE SESSION TO ADMIN;

GRANT GUEST TO guest1;
GRANT GUEST TO guest2;
GRANT GUEST TO guest3;

GRANT MESAS TO mesas1;
GRANT MESAS TO mesas2;
GRANT MESAS TO mesas3;
GRANT MESAS TO mesas4;

GRANT IT TO it1;
GRANT IT TO it2;
GRANT IT TO it3;

GRANT ADMIN TO admin1;
GRANT ADMIN TO admin2;


GRANT SELECT ON ACTA TO guest1 WITH GRANT OPTION;
GRANT SELECT ON DEPARTAMENTO TO guest1 WITH GRANT OPTION;
GRANT SELECT ON ELECCION TO guest1 WITH GRANT OPTION;
GRANT SELECT ON MUNICIPIO TO guest1 WITH GRANT OPTION;
GRANT SELECT ON PARTIDO TO guest1 WITH GRANT OPTION;
GRANT SELECT ON VOTO TO guest1 WITH GRANT OPTION;
GRANT CREATE VIEW TO guest1;

GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO guest2;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO guest3;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO mesas1;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO mesas2;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO mesas3;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO mesas4;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO it1;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO it2;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO it3;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO admin1;
GRANT SELECT ON GUEST1.VOTOSPRESIDENTE TO admin2;






