CREATE OR REPLACE VIEW GUEST1.VOTOSPRESIDENTE AS
	SELECT
		d.NOMBRE_DEPTO AS "Departamento",
		m.NOMBRE_MUNI AS "Municipio",
		p.NOMBRE_PART AS "Partido",
		SUM(v.VOTO_CANTIDAD) AS "No. Votos"
	FROM
		ELECCIONES.VOTO v,
		ELECCIONES.ACTA a,
		ELECCIONES.PARTIDO p,
		ELECCIONES.DEPARTAMENTO d,
		ELECCIONES.MUNICIPIO m
	WHERE
		a.NUMERO_MESA = v.VOTO_MESA
		AND a.TIPO_ELECCION = v.VOTO_ELECCION
		AND p.CODIGO_PART = v.VOTO_PARTIDO
		AND m.CODIGO_MUNI = a.MUNICIPIO
		AND d.CODIGO_DEPTO = a.DEPARTAMENTO
		AND m.DEPTO_MUNI = d.CODIGO_DEPTO
	GROUP BY d.NOMBRE_DEPTO, m.NOMBRE_MUNI, p.NOMBRE_PART
	ORDER BY d.NOMBRE_DEPTO, m.NOMBRE_MUNI, p.NOMBRE_PART
;

SELECT * FROM ELECCIONES.VOTOSPRESIDENTE;
SELECT * FROM ELECCIONES.DEPARTAMENTO d;
