
CREATE TABLESPACE ELECCIONESTBS DATAFILE 'ELECCIONESDTF.tbs' SIZE 250M AUTOEXTEND ON MAXSIZE 500M;

SELECT * FROM USER_TABLESPACES;

CREATE USER ELECCIONES IDENTIFIED BY ELECCIONES DEFAULT TABLESPACE ELECCIONESTBS ACCOUNT UNLOCK;

GRANT "DBA" TO "ELECCIONES" WITH ADMIN OPTION;




CREATE TABLESPACE ESTADISTICASTBS DATAFILE 'ESTADISTICASTBS.tbs' SIZE 250M AUTOEXTEND ON MAXSIZE 500M;

CREATE USER ESTADISTICAS IDENTIFIED BY ESTADISTICAS DEFAULT TABLESPACE ESTADISTICASTBS ACCOUNT UNLOCK;

GRANT "DBA" TO "ESTADISTICAS" WITH ADMIN OPTION;


expdp system/Panda12345@XE dumpfile=jugador_equipo_30.dmp tables=ESTADISTICAS.Jugador,ESTADISTICAS.Equipo content=metadata_only

impdp system/Panda12345@XE dumpfile=jugador_equipo_30.dmp


expdp system/Panda12345@XE dumpfile=liga_jornada_30.dmp tables=ESTADISTICAS.Liga,ESTADISTICAS.Jornada

impdp system/Panda12345@XE dumpfile=liga_jornada_30.dmp




CREATE TABLESPACE ESTADISTICASTBS2 DATAFILE 'ESTADISTICASTBS2.tbs' SIZE 250M AUTOEXTEND ON MAXSIZE 500M;

CREATE USER ESTADISTICAS2 IDENTIFIED BY ESTADISTICAS2 DEFAULT TABLESPACE ESTADISTICASTBS2 ACCOUNT UNLOCK;

GRANT "DBA" TO "ESTADISTICAS2" WITH ADMIN OPTION;
