
SELECT * FROM ELECCIONES.VOTOSPRESIDENTE;
SELECT * FROM ELECCIONES.DEPARTAMENTO d;

SELECT * FROM ELECCIONES.ELECCION;
UPDATE ELECCIONES.ELECCION SET NOMBRE_ELE = 'lel' WHERE CODIGO_ELE = 2;
UPDATE ELECCIONES.ELECCION SET NOMBRE_ELE = 'Alcalde' WHERE CODIGO_ELE = 2;
INSERT INTO ELECCIONES.ELECCION VALUES (3,'lel');
DELETE FROM ELECCIONES.ELECCION WHERE CODIGO_ELE = 3;


CREATE OR REPLACE VIEW VOTOSPRESIDENTE AS
	SELECT
		d.NOMBRE_DEPTO AS "Departamento",
		m.NOMBRE_MUNI AS "Municipio",
		p.NOMBRE_PART AS "Partido",
		SUM(v.VOTO_CANTIDAD) AS "No. Votos"
	FROM
		ELECCIONES.VOTO v,
		ELECCIONES.ACTA a,
		ELECCIONES.PARTIDO p,
		ELECCIONES.DEPARTAMENTO d,
		ELECCIONES.MUNICIPIO m,
		ELECCIONES.ELECCION e
	WHERE
		a.NUMERO_MESA = v.VOTO_MESA
		AND a.TIPO_ELECCION = v.VOTO_ELECCION
		AND p.CODIGO_PART = v.VOTO_PARTIDO
		AND m.CODIGO_MUNI = a.MUNICIPIO
		AND d.CODIGO_DEPTO = a.DEPARTAMENTO
		AND m.DEPTO_MUNI = d.CODIGO_DEPTO
		AND e.CODIGO_ELE = a.TIPO_ELECCION 
		AND e.NOMBRE_ELE = 'Presidente'
	GROUP BY d.NOMBRE_DEPTO, m.NOMBRE_MUNI, p.NOMBRE_PART
	ORDER BY d.NOMBRE_DEPTO, m.NOMBRE_MUNI, p.NOMBRE_PART
WITH READ ONLY
;

